### ISSUE TITLE
step by step guidance for run this project

### ISSUE THREAD

**Issue by iamitsrivastav** [chakshu-dhannawat/Face-Liveness-Detection#1]
hey! pls give me a guidance to setup and run this project step by step.
if possible then pls make a YouTube video to setup for Bigners.

**Comment by chakshu-dhannawat** [comment]
Hey! To run this, you simply need to run the 'main_code_only_liveness_detection.py' file, no extra downloads will be required, it uses the pre trained weights of the uploaded model.

If you want to train your own model, you will need a custom dataset for that. Feel free to contact me if you need any help in that regard.

Also, I am not a youtuber so no video.
